receipts-system/main/default/objects/Receipt_Serie__c/Receipt_Serie__c.object-meta.xml
<CustomObject>
    <label>Receipt Serie</label>
    <nameField>
        <displayFormat>SERIE-{00000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receipts-system/main/default/objects/Receipt_Serie__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

receipts-system/main/default/objects/Receipt_Serie__c/fields/Last_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Number__c</fullName>
    <label>Último Número</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

receipts-system/main/default/objects/Receipt_Serie__c/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <label>Prefixo</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

receipts-system/main/default/objects/Receipt_Serie__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Tipo de Transação</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organizational</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

receipts-system/main/default/objects/Receipt_Serie__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Ano</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

receipts-system/main/default/classes/RCPT_SerieFabricator_BATCH.cls
public with sharing class RCPT_SerieFabricator_BATCH implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    public Integer insertSize;
    public String nextYear;
    public String thisYear;

    public void execute(SchedulableContext SC) { 
        Database.executeBatch( new RCPT_SerieFabricator_BATCH(), 200 );
    }

    public RCPT_SerieFabricator_BATCH(){
        this.insertSize = 0;
        this.nextYear = String.valueOf(Date.today().year()+1);
        this.thisYear = String.valueOf(Date.today().year());
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT ID, Prefix__c, Transaction_Type__c, Active__c 
                                        FROM Receipt_Serie__c
                                        WHERE Active__c = true
                                        AND Year__c = :this.thisYear]);
    }
    public void execute(Database.BatchableContext BC, List<Receipt_Serie__c> scope){
        List<Receipt_Serie__c> toInsert = new List<Receipt_Serie__c>();
        try{
            for (Receipt_Serie__c serie : scope) {
                Receipt_Serie__c newSerie = serie.clone(false);
                newSerie.Last_Number__c = 0;
                newSerie.Year__c = this.nextYear;
                toInsert.add(newSerie);
            }
            insert toInsert;
            this.insertSize =+ toInsert.size();
        }
        catch(Exception e){
            new DL_DebugLog_CTRL('Recibos',
                                'RCPT_SerieFabricator_BATCH',
                                'execute', 
                                'catchStatement', 
                                null, 
                                null, 
                                JSON.serializePretty(toInsert), 
                                e.getMessage() + ' ' + e.getStackTraceString(), 
                                null, 
                                false, 
                                false).publish();
        }
    }
    public void finish(Database.BatchableContext BC){
        new DL_DebugLog_CTRL('Recibos',
                                'RCPT_SerieFabricator_BATCH',
                                'finish', 
                                null, 
                                null, 
                                null, 
                                'Inserted ' + this.insertSize + ' new series for the year '+String.valueOf(Date.today().year()+1), 
                                null, 
                                null, 
                                true, 
                                false).publish();
    }
}