receipts-system/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RCPT-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receipts-system/main/default/objects/Receipt__c/fields/Encrypted_Id__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Encrypted Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

receipts-system/main/default/objects/Receipt__c/fields/Original_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_Amount__c</fullName>
    <label>Original Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

receipts-system/main/default/objects/Receipt__c/fields/Receipt_Number__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Number__c</fullName>
    <label>Receipt Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

receipts-system/main/default/objects/Receipt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>To Validate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

receipts-system/main/default/objects/Receipt__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organizational</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

receipts-system/main/default/classes/RCPT_ReceiptPDF_CTRL.cls
public class RCPT_ReceiptPDF_CTRL {
    
    public Receipt__c receipt 	{get;set;}
 
    public RCPT_ReceiptPDF_CTRL(){
        try {
            String receiptId = ApexPages.currentPage().getParameters().get('id');
            if( String.isBlank(receiptId) ){
                System.debug(LoggingLevel.ERROR, 'Invalid Object ID');
            } else {
                this.receipt = [SELECT ID, Encrypted_Id__c, Transaction_Type__c, Status__c, Original_Amount__c, Name__c, Email__c, Payment_Date__c, Receipt_Number__c
                                FROM Receipt__c 
                                WHERE Encrypted_Id__c =: receiptId 
                                LIMIT 1];
            }
        }catch (Exception e) {
            System.debug(e.getCause() + ' ' + e.getLineNumber() + ' ' + e.getMessage() + ' ' + e.getStackTraceString());
        }
    }
}