receipts-system/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RCPT-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receipts-system/main/default/objects/Receipt__c/fields/Encrypted_Id__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Encrypted Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

receipts-system/main/default/objects/Receipt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>To Validate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

receipts-system/main/default/objects/Receipts_System_Mapping__mdt/Receipts_System_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Receipts System Mapping</label>
    <pluralLabel>Receipts System Mappings</pluralLabel>
</CustomObject>

receipts-system/main/default/objects/Receipts_System_Mapping__mdt/fields/Destiny_Field__c.field-meta.xml
<CustomField>
    <fullName>Destiny_Field__c</fullName>
    <label>Destiny Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

receipts-system/main/default/classes/RCPT_ReceiptData_OBJ.cls
public with sharing class RCPT_ReceiptData_OBJ {
    public Receipt__c receiptObject    {get;set;}
    public String action               {get;set;}
    public String oldReceipt           {get;set;}

    public RCPT_ReceiptData_OBJ(SObject inputObject, String oldReceipt, String action) {
        this.receiptObject = buildReceipt(inputObject);//inputObject != null ? buildReceipt(inputObject) : null;
        this.action = action;
        this.oldReceipt = oldReceipt;
    }
    private static Receipt__c buildReceipt(SObject inputObject){
        Map<String, Receipts_System_Mapping__mdt> customMetadataRecords = Receipts_System_Mapping__mdt.getAll();
        Receipt__c receiptObject = new Receipt__c();
        receiptObject.Status__c = 'Pending';
        receiptObject.Encrypted_Id__c = setEncryptedId();
        if(inputObject==null){
            return receiptObject;
        }
        for (Receipts_System_Mapping__mdt metadata : customMetadataRecords.values()) {
            if(inputObject.get(metadata.Source_Field__c) != null){
                    receiptObject.put(metadata.Destiny_Field__c, inputObject.get(metadata.Source_Field__c));
            }
        }
        return receiptObject;
    }
    private static String setEncryptedId(){
        UUID randomUUID = UUID.randomUUID();
        return randomUUID.toString();
    }
}