receipts-system/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RCPT-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receipts-system/main/default/objects/Receipt__c/fields/Encrypted_Id__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Encrypted Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

receipts-system/main/default/objects/Receipt__c/fields/Original_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_Amount__c</fullName>
    <label>Original Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

receipts-system/main/default/objects/Receipt__c/fields/Receipt_Number__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Number__c</fullName>
    <label>Receipt Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

receipts-system/main/default/objects/Receipt__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>To Validate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

receipts-system/main/default/objects/Receipt__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organizational</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

receipts-system/main/default/objects/Receipt_Serie__c/Receipt_Serie__c.object-meta.xml
<CustomObject>
    <label>Receipt Serie</label>
    <nameField>
        <displayFormat>SERIE-{00000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

receipts-system/main/default/objects/Receipt_Serie__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

receipts-system/main/default/objects/Receipt_Serie__c/fields/Last_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Number__c</fullName>
    <label>Último Número</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

receipts-system/main/default/objects/Receipt_Serie__c/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <label>Prefixo</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

receipts-system/main/default/objects/Receipt_Serie__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Tipo de Transação</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Organizational</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

receipts-system/main/default/objects/Receipt_Serie__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Ano</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

receipts-system/main/default/classes/RCPT_Process_TEST.cls
@isTest
public with sharing class RCPT_Process_TEST {
    @TestSetup
    static void makeData(){
        Receipt_Serie__c serie = new Receipt_Serie__c();
        serie.Prefix__c = 'TT';
        serie.Last_Number__c = 0;
        serie.Year__c = String.valueOf(Date.today().year());
        serie.Transaction_Type__c = 'Individual';
        serie.Active__c = true;
        insert serie;
    }
    @isTest 
    public static void createReceiptFlow() {
        SObject obj ;
        RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ input = new RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ();
        input.transactionSObject = obj;
        input.cancelReceiptId = null;
        input.actionType = 'create';
        List<RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ> flowList = new List<RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ>{input};
        Test.startTest();
            List<RCPT_FlowData_OBJ.RCPT_OutputVariables_OBJ> output = RCPT_Process_CTRL.invocableProcessMethod(flowList);
        Test.stopTest();
        List<Receipt__c> updatedReceipts = [SELECT Id, Receipt_Number__c, Status__c FROM Receipt__c];
        Assert.areEqual(1, updatedReceipts.size(), 'Should have created Receipt');
    }
    @isTest 
    public static void cancelReceiptFlow() {
        Receipt__c receipt = new Receipt__c();
        receipt.Status__c = 'Active';
        receipt.Encrypted_Id__c = '123';
        receipt.Name__c = 'Test';
        receipt.Original_Amount__c = 25;
        receipt.Transaction_Type__c = 'Individual';
        receipt.Payment_Date__c = Date.today();
        insert receipt;
        RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ input = new RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ();
        input.transactionSObject = null;
        input.cancelReceiptId = receipt.Id;
        input.actionType = 'cancel';
        List<RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ> flowList = new List<RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ>{input};
        Test.startTest();
            List<RCPT_FlowData_OBJ.RCPT_OutputVariables_OBJ> output = RCPT_Process_CTRL.invocableProcessMethod(flowList);
        Test.stopTest();
        List<Receipt__c> updatedReceipts = [SELECT Id, Receipt_Number__c, Status__c FROM Receipt__c];
        Assert.areEqual('Cancelled', updatedReceipts[0].Status__c, 'Should have cancelled Receipt');
    }
    @isTest 
    public static void updateReceipt() {
        Receipt__c receipt = new Receipt__c();
        receipt.Status__c = 'Active';
        receipt.Encrypted_Id__c = '123';
        receipt.Name__c = 'Test';
        receipt.Original_Amount__c = 25;
        receipt.Transaction_Type__c = 'Individual';
        receipt.Payment_Date__c = Date.today();
        insert receipt;
        SObject obj;
        RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ input = new RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ();
        input.transactionSObject = obj;
        input.cancelReceiptId = receipt.Id;
        input.actionType = 'update';
        List<RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ> flowList = new List<RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ>{input};
        Test.startTest();
            List<RCPT_FlowData_OBJ.RCPT_OutputVariables_OBJ> output = RCPT_Process_CTRL.invocableProcessMethod(flowList);
        Test.stopTest();
        List<Receipt__c> canceledReceipts = [SELECT Id, Receipt_Number__c, Status__c FROM Receipt__c Where Id = :receipt.Id];
        Assert.areEqual('Cancelled', canceledReceipts[0].Status__c, 'Should have cancelled first Receipt');
        List<Receipt__c> updatedReceipts = [SELECT Id, Receipt_Number__c, Status__c FROM Receipt__c Where Id != :receipt.Id];
        Assert.areEqual(1, updatedReceipts.size(), 'Should have created new Receipt');
    }
    @isTest 
    public static void ErrorReceiptFlow() {
        SObject obj ;
        RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ input = new RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ();
        input.transactionSObject = obj;
        input.cancelReceiptId = null;
        input.actionType = 'noSupport';
        List<RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ> flowList = new List<RCPT_FlowData_OBJ.RCPT_InputVariables_OBJ>{input};
        Test.startTest();
            List<RCPT_FlowData_OBJ.RCPT_OutputVariables_OBJ> output = RCPT_Process_CTRL.invocableProcessMethod(flowList);
        Test.stopTest();
        List<Debug_Log__c> log = [SELECT Id, Error_Message__c, Success__c FROM Debug_Log__c WHERE Source__c = 'Recibos'];
        Assert.areEqual(1, log.size(), 'Should have created Error Log');
        Assert.isNotNull(log[0].Error_Message__c, 'Should have Error Message');
        Assert.isFalse(log[0].Success__c, 'Should have failed');
    }
    @isTest 
    public static void testReceiptSerieSuccess() {
        Receipt__c receipt = new Receipt__c();
        receipt.Status__c = 'Pending';
        receipt.Encrypted_Id__c = '123';
        receipt.Name__c = 'Test';
        receipt.Original_Amount__c = 25;
        receipt.Transaction_Type__c = 'Individual';
        receipt.Payment_Date__c = Date.today();
        insert receipt;
        Test.startTest();
            RCPT_SetSerieNumber_CTRL.invocableProcess(new List<Receipt__c>{receipt});
        Test.stopTest();
        List<Receipt__c> updatedReceipts = [SELECT Id, Receipt_Number__c, Status__c FROM Receipt__c WHERE Id = :receipt.Id];
        Assert.isNotNull(updatedReceipts[0].Receipt_Number__c, 'Should have updated Receipt Number');
    }
    @isTest 
    public static void testReceiptSerieFailure() {
        Receipt__c receipt = new Receipt__c();
        receipt.Status__c = 'Pending';
        receipt.Encrypted_Id__c = '123';
        receipt.Name__c = 'Test';
        receipt.Original_Amount__c = 25;
        receipt.Transaction_Type__c = 'Individual';
        receipt.Payment_Date__c = Date.newInstance(2024, 1, 1);
        insert receipt;
        Test.startTest();
            new RCPT_SetSerieNumber_CTRL(new List<Receipt__c>{receipt}, 1).process();
        Test.stopTest();
        List<Debug_Log__c> log = [SELECT Id, Error_Message__c FROM Debug_Log__c WHERE Source__c = 'Recibos'];
        Assert.areEqual(2, log.size(), 'Should have created 2 error Logs, one for the first another for the retry');
    }
}